name: Build and Release Modpack

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run main.ts
        env:
          AUTO_GITHUB_RELEASE: '1'
          AUTO_MR_PUBLISH: '1'
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: deno run --allow-net --allow-read --allow-write --allow-env main.ts
